title               : Mostafa Dehghani
description         : >-                               # >- means to ignore newlines until "url:"
                      Research Scientist at Google Brain.

url                 : "https://github.com/MostafaDehghani/MostafaDehghani.github.io"
repository          : MostafaDehghani/MostafaDehghani.github.io

email: dehghani@google.com
twitter: m__dehghani
github_user: MostafaDehghani
instagram: mo0osina


exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock